version: "3"
services:
  app:
    build: .
    container_name: fake-product
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/app-db
      NODE_ENV: production
    ports:
      - "8080:8080"

  db:
    image: postgres:13.0
    container_name: fake-product-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql   
    env_file:
      - db.env  